theme: minima
title: Passerby_A's Blog
subtitle: A place to share my thoughts
description: This is my personal blog where I write about technology, life, and more.
keywords: [blog, personal, technology, life]
author: Passerby_A
email: 780551528@qq.com
